### PR TITLE
html-tasks Ray-code2020 emrerdem1

### PR DESCRIPTION
**Pull request by emrerdem1**
Hi Louis! Sorry for the late edit, I fixed the type of files and directories as well as excluded the css task to make a new pull request with it.

If this pull request contains any mistakes, please let us know.

Sincerely.

### CODE REVIEW

**Comment by emrerdem1** [comment]
I guess I cannot make two seperate pull request, so it automatically added my last commit to this pull request, too.

**Comment by louisrli** [comment]
nvm i see. you can make two separate pull requests, but you need one git branch for each :)

**Comment by louisrli** [comment]
but don't worry about it. i will review this one.

**Comment by louisrli** [comment]
it still contains the .vs files, otherwise it looks good 

(always proofread your PR: https://github.com/ReCoded-Org/bootcamp-istanbul-2020mar/pull/74/files)

https://stackoverflow.com/questions/6535362/gitignore-after-commit

**Comment by emrerdem1** [comment]
Thank you so much! Made a new pull request with a new branch. :)

**Comment by louisrli** [comment]
lgtm

**Pull request merged**
