### PR TITLE
HTML Quiz DONE!

### PR DESCRIPTION
**Pull request by Straw-Hat-Luffy24**

### CODE REVIEW

**Comment by louisrli** [comment]
@Dara-D 
by convention, we avoid using `&` and other special characters in filenames. usually we use hyphens (`-`) and sometimes underscores (depends on the company and convention). can you fix your directory and file names so that they don't have these?

hint: see `git mv` command

(don't worry, another group did the same thing)
https://github.com/ReCoded-Org/bootcamp-istanbul-2020mar/pull/49#issuecomment-605651339

**Comment by Straw-Hat-Luffy24** [comment]
Problem Fixed !, I will keep that in mind.

**Comment by Straw-Hat-Luffy24** [comment]
Problem Fixed! I changed both the directory to Dara-Halit and the file names to be  quiz0.html and quiz1.html

**Comment by louisrli** [comment]
lgtm

**Pull request merged**
