### PR TITLE
map-reduce-exercises maher-suleyman kamalbakour

### PR DESCRIPTION
**Pull request by maher-suleyman**

### CODE REVIEW

**Comment by louisrli** [comment]
hmm...there's a lot of random other stuff in here :)

**Comment by louisrli** [comment]
lets fıx thıs one

**Comment by maher-suleyman** [comment]
could you please tell me how to fix it?

**Comment by louisrli** [comment]
`git checkout master` (assuming master is clean)

then

`git checkout map-reduce-branch <path to files you want>`

i would first make sure you get the idea of isolating files, and then google "how to copy files from one branch to another in git"

**Comment by louisrli** [comment]
^ both being able to search the solution and being able to do this is fairly important so give it a try

**Pull request closed without merging**
