### PR TITLE
CSS-task0 Ahripol Samah-Mustafa

### PR DESCRIPTION
**Pull request by Samah-Mustafa**
Gunsu-Samah

### CODE REVIEW

**Comment by louisrli** [comment]
hi samah, there are some instructions about how to name your pull request. can you please fix that?

also, no spaces in file/directory names :)

**Comment by Samah-Mustafa** [comment]
Is is Ok to name it Samah-Gunsu?

**Comment by louisrli** [comment]
no, it needs to be your github usernames, because i will use a program to automatically check who has submitted :)

**Comment by Samah-Mustafa** [comment]
CSS-task0 Ahripol Samah-Mustafa

**Comment by Samah-Mustafa** [comment]
I hope it's Ok now

**Comment by louisrli** [comment]
there are still spaces in the directory names but just remember for next time :)

**Pull request merged**
