### PR TITLE
css-task0 reficca lilas-saleh

### PR DESCRIPTION
**Pull request by reficca**
Lilas&Refia

### CODE REVIEW

**Comment by reficca** [comment]
task1 for lilas&refia

**Comment by louisrli** [comment]
by convention, we should avoid using `&` and other special characters in filenames. usually we use hyphens (`-`) and sometimes underscores (depends on the company and convention). can you fix your directory and file names so that they don't have these?

hint: see `git mv` command

**Comment by louisrli** [comment]
looks good. next time let's split each task into its own PR for our tracking purposes :) (i know this is tricky as it will require branching but it's good practice)

**Comment by louisrli** [comment]
ah sorry, ignore the comment about splitting the tasks into its own PR. i got confused by my own class numbering (class4 vs class5) :)

**Comment by louisrli** [comment]
actually, maybe not...did you forget to add `style.css`? 

`    <link href="style.css" rel="stylesheet" type="text/css" />`

i see this but no style.css file

**Comment by reficca** [comment]
we added that link tag at our first practice with the document just as a draft, there was no css file back then actually. so it was just an html task back at class4 on saturday, right? for class 5 lilas created a pull request including the css file that we worked on class5, on tuesday.

**Pull request merged**
