### PR TITLE
Aydın Davutoğlu and Moutaman Mert Hocaoğlu

### PR DESCRIPTION
**Pull request by Davut97**
added index.html

### CODE REVIEW

**Comment by louisrli** [comment]
the file is in the wrong directory. please fix :)

**Comment by Davut97** [comment]
is it in the right directory now?

**Comment by louisrli** [comment]
no :) look at the class4 directory to see examples of what others have done

**Comment by Davut97** [comment]
i hope this is right now :)

**Comment by louisrli** [comment]
Nope. Please go to files changed and look at what files are added in this pull request. Needs to be cleaned up. "Proofreading" :)

**Comment by Davut97** [comment]
deleted task1.png as requested

**Comment by louisrli** [comment]
LGTM! thank you

**Pull request merged**
