### PR TITLE
added new files!

### PR DESCRIPTION
**Pull request by yamoonz**

### CODE REVIEW

**Comment by louisrli** [comment]
hi yaman, yay! unfortunately you have two extra files that need to be fixed, can you delete them and recommit. see this page for a perspective of what i'm looking at:
https://github.com/ReCoded-Org/bootcamp-istanbul-2020mar/pull/55/files

you should only have the task files but there appear to be extras

**Comment by yamoonz** [comment]
Sorry for the mistake But I couldn't find any extra filesUnless you meant the. Subfolders? Which are Bootcamp-Istanbul-2020mar and exercises? Sent from my Huawei phone-------- Original message --------From: Louis Li <notifications@github.com>Date: Sun, Mar 29, 2020, 6:12 PMTo: ReCoded-Org/bootcamp-istanbul-2020mar <bootcamp-istanbul-2020mar@noreply.github.com>Cc: Yaman Kahveci <yamooonz@gmail.com>, Author <author@noreply.github.com>Subject: Re: [ReCoded-Org/bootcamp-istanbul-2020mar] added new files! (#55)
hi yaman, yay! unfortunately you have two extra files that need to be fixed, can you delete them and recommit. see this page for a perspective of what i'm looking at:
https://github.com/ReCoded-Org/bootcamp-istanbul-2020mar/pull/55/files
you should only have the task files but there appear to be extras

**Comment by louisrli** [comment]
Yes, I meant the subfolders. Those need to be removed from the pull request

**Comment by yamoonz** [comment]
I think now it's okay? Sent from my Huawei phone-------- Original message --------From: Louis Li <notifications@github.com>Date: Sun, Mar 29, 2020, 8:38 PMTo: ReCoded-Org/bootcamp-istanbul-2020mar <bootcamp-istanbul-2020mar@noreply.github.com>Cc: Yaman Kahveci <yamooonz@gmail.com>, Author <author@noreply.github.com>Subject: Re: [ReCoded-Org/bootcamp-istanbul-2020mar] added new files! (#55)
Yes, I meant the subfolders. Those need to be removed from the pull request

**Comment by louisrli** [comment]
It looks like you deleted everyone else's files now! :O

**Comment by louisrli** [comment]
Before the next round of review, please check https://github.com/ReCoded-Org/bootcamp-istanbul-2020mar/pull/55/files -- from here you can preview what your change looks like (and "proofread" the pull request -- double check that it only contains changes to the files that you want)

**Pull request merged**
