### PR TITLE
first

### PR DESCRIPTION
**Pull request by ilydcndr**

### CODE REVIEW

**Comment by louisrli** [comment]
Hi Ilayda,

Your files are in `class1/ilayda/boilWater.md `

But they should be in `class1/<your trainer>/boilWater.md`

You can move them using the `mv` command on the terminal.

Find the top directory (e.g., from home, do `cd bootcamp-istanbul-2020mar`)

Then you can move the files as such:
`mkdir class1/<my trainer>/ilayda`
` mv class1/ilayda/* class1/<my trainer>/ilayda`

**Comment by ilydcndr** [comment]
Thank you Louis, I will 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by louisrli** [comment]
Hi Ilayda, when you have time, can you fix this pull request so that we can merge it in? :)

**Comment by ilydcndr** [comment]
I think,I did :)
________________________________
Gönderen: Louis Li <notifications@github.com>
Gönderildi: 25 Mart 2020 Çarşamba 15:53
Kime: ReCoded-Org/bootcamp-istanbul-2020mar <bootcamp-istanbul-2020mar@noreply.github.com>
Bilgi: ilydcndr <ilaydacundar@hotmail.com>; Author <author@noreply.github.com>
Konu: Re: [ReCoded-Org/bootcamp-istanbul-2020mar] first (#22)


Hi Ilayda, when you have time, can you fix this pull request so that we can merge it in? :)

**Comment by louisrli** [comment]
Thanks!

**Pull request merged**
