### PR TITLE
javascript-task0 ahripol hassandayem

### PR DESCRIPTION
**Pull request by hassandayem**
JS-exercise-Gunsu&Hassan

### CODE REVIEW

**Comment by louisrli** [comment]
please follow the format described in slack

**Comment by louisrli** [comment]
also i believe this is class6

**Comment by hassandayem** [comment]
> please follow the format described in slack

Sorry Louis :sweat_smile: 
I changed it.

**Comment by hassandayem** [comment]
> also i believe this is class6

I actually in class6, but I don't know why are my previous commits from clas5 appear here.

**Comment by louisrli** [comment]
LGTM

**Pull request merged**
