### PR TITLE
Added Task 04 from Mahir & Omar

### PR DESCRIPTION
**Pull request by maher-suleyman**

### CODE REVIEW

**Comment by louisrli** [comment]
the files are in the wrong directory (they are in the top-level one). please fix :)

**Comment by louisrli** [comment]
quick followup to fix this :)

**Comment by maher-suleyman** [comment]
I have fetched and updated my repository and added class4 and class5 tasks.

**Comment by louisrli** [comment]
sorry accidentally left an old comment. lgtm!

**Pull request merged**
